import type { Article } from './index.js';

const article: Article = {
  id: 'civil-disobedience',
  title: 'A Letter from the North Field',
  author: 'Helena Voss',
  estimatedMinutes: 4,
  body: `I am writing this from the small wooden hut at the edge of the north field, where I have been living, more or less alone, for the better part of three months. The hut belongs to a friend who uses it in summer and lets me use it in winter, on the understanding that I will keep the stove going and write to her occasionally to confirm that the roof is still where she left it. The roof is still where she left it. The stove is going. I have been writing to her every Sunday and to you, now, on a Wednesday, because I have been thinking about something I want to put down before the thought slips loose.

The field is not, by any standard, a remarkable piece of land. It slopes gently toward a creek that runs only in spring, and the soil is more clay than I would like, and the previous tenant ran sheep on it for so many years that the grass has not entirely recovered. The trees along the western edge are the usual mix of scrub oak and elder, with one taller pine that has, judging by its bark, survived at least one significant fire. There is no view to speak of. The horizon is a low ridge that blocks the sunset. The neighbors, such as they are, live a quarter mile down the road and keep largely to themselves.

What I have come to understand, in the time I have been here, is that the unremarkableness is the point. I came out here, originally, with a vague notion that solitude would clarify some questions I had been carrying. I had imagined, I think, that the landscape would offer me grand vistas and the grand vistas would do some of the work of thinking for me. It has not turned out that way. The landscape is, mostly, brown. The wind, for weeks at a time, blows from the same direction. The same five birds visit the same feeder, in roughly the same order, and the only event of any drama in my first month was a barn owl that struck the kitchen window one night, recovered itself on the porch railing for about ninety seconds, and flew off looking embarrassed. (I have since drawn the curtains.)

And yet. The questions I came with are, slowly, answering themselves, not because the landscape is dramatic but because the landscape is patient. I have learned, out here, that one of the things I had been doing in my old life was filling every quiet moment with a small distraction. A glance at the phone, a cup of tea I did not really want, a quick check of the news to confirm that the world was still complicated. The distractions felt harmless because they were small. They were not harmless. They were the way I avoided the questions. And the questions, denied any quiet in which to surface, had been growing more insistent and less articulate, in the way that an unattended baby grows more insistent and less articulate, until the only thing it can do is cry.

Out here there are no small distractions. There is the stove, which requires real attention or it goes out. There is the water, which I have to carry from a hand pump and which takes about as long as you would expect. There is the radio, which I listen to for an hour in the evening and otherwise leave alone. The result is that my questions have had nowhere to go but up, into consciousness, where I have been able to look at them. Some of them turned out to be smaller than I thought. A few turned out to be larger. One or two turned out to be different questions altogether, wearing the costume of the original.

I do not want to romanticize this. The hut is cold. I am often bored. I have caught myself, more than once, missing the sound of traffic, which I had previously believed I disliked. The owl made me jump. The clay soil makes the path impassable for two days after every rain. There is no version of this life that scales, and I am not proposing it as a model. I will go back to the city in the spring, and I will be glad to. But I will go back changed in at least one specific way: I will know, from having lived without them, what the small distractions were costing me, and I will be slower to reach for them.

You asked, in your last letter, whether I was lonely. I have thought about that question for a week, and the honest answer is that I am not, exactly, but I am alone, which is a different thing, and I have come to believe that most adults in our society have very little experience of being alone in this particular way and could probably use more of it. Whether you would like more of it I cannot say. I would not have predicted, six months ago, that I would like it. But I am writing to you now from a small wooden hut at the edge of a brown field, with a stove that is doing its work and a kettle that is about to whistle, and I am, against my own expectations, content.`,
};

export default article;
