import type { Article } from './index.js';

const article: Article = {
  id: 'walden-excerpt',
  title: 'On the Practice of Looking',
  author: 'Hugo Lange',
  estimatedMinutes: 5,
  body: `When I was nineteen I worked for a summer in a small printing shop on the edge of a town I no longer live in. The owner was a man named Albers, whose name I have changed slightly here because he is still alive and I would not want to embarrass him. He was the most attentive person I have ever met. He was also, by ordinary standards, not particularly gifted. He printed wedding invitations and funeral programs and the occasional handbill for a local theater. The work was repetitive and the equipment was old. But he did the work better than anyone I have seen do anything before or since, and I have spent the years afterward trying to understand why.

The shop opened at seven and closed at five, and Albers spent most of those ten hours within reaching distance of the same press. He fed it paper, he cleaned it, he adjusted the rollers, he examined the proofs under a green-shaded lamp that hung from a brass chain. The lamp was not strictly necessary. The shop had perfectly good overhead lighting. But Albers had decided, at some point in his career, that the green-shaded lamp produced a kind of light that revealed certain inconsistencies in the inking, and he had never seen any reason to change his mind. So the lamp stayed, and he leaned into it many times a day, his glasses sliding down his nose, his thumb pressing gently against the corner of the proof to keep it flat.

I learned, working alongside him, that there are at least two ways to do a task. There is the way that completes the task, and there is the way that completes the task while also continuing to teach you about the task. Most of us, most of the time, do the first kind. We have to. There are too many tasks in a day to give each one the second kind of attention. But Albers, somehow, did the second kind for nearly everything that crossed his bench. He was not faster than other printers I would later work with. In some respects he was slower. But he had, after forty years of printing, a knowledge of paper and ink and pressure that the faster printers did not have, and the difference showed up in places that customers noticed and many places that they did not.

This is, I think, what people mean when they talk about craft, although the word has been worn down by overuse. Craft is not perfectionism, which is a kind of fear dressed up as standards. Craft is the willingness to pay attention to the work itself, separate from the question of whether the work is done. It is a stance toward the object in your hands. It says: you are not merely an instrument of my completion. You are a thing in your own right, and you have something to tell me, and I am going to listen even though no one is paying me to listen and no one will know whether I have listened.

I have noticed, in my own working life, that the days when I treat my work this way are the days when I come home tired in a useful way, and the days when I treat my work as a series of obstacles to be hurried past are the days when I come home tired in a depleting way. The amount of work accomplished is, weirdly, similar. Sometimes the careful days produce less. But the careful days deposit something in me that the rushed days do not, and that something accumulates, slowly, into what I can only describe as a relationship with the work. I do not feel, on the careful days, that the work is using me up. I feel that the work and I are getting to know each other.

The shop closed in the autumn of my twentieth year. Digital design had been encroaching for a decade, and the wedding invitation business had moved entirely to online templates by then. Albers found another shop to take in his press, which he loved more than I was prepared for at the time, and he retired to a small apartment near his daughter. I saw him once, years later, at a regional book fair, examining a letterpress broadside with the same posture he had used at the green-shaded lamp. His glasses had slid to the same place on his nose. His thumb pressed the corner of the broadside in the same patient way. He did not see me, and I did not interrupt him.

I have thought about that posture often. It is the posture of someone for whom the object in front of him still has something to offer. It is, I have come to believe, the most valuable posture a working person can cultivate, more valuable than ambition and more valuable than productivity, because it is the posture out of which good work actually emerges. The other postures produce output. This one produces meaning. I am not sure how to teach it. I am not sure anyone taught it to Albers. But I know it when I see it, and I know how rare it is, and I am writing this in part to honor a man who showed me, without ever saying so, that there is a kind of attention you can bring to ordinary work that turns the ordinary work into something else.`,
};

export default article;
